resolver: lts-22.13

ghc-options:
  "$everything": -haddock

packages:
- mello

extra-deps:
- bowtie-0.3.1
- daytripper-0.3.1
- falsify-0.2.0@r1
# TODO switch on release
# - looksee-0.6.0
# - looksee-trip-0.6.0
- git: git@github.com:ejconlon/looksee.git
  commit: b854f35a983a911f0c7a1d917f34dfb104f2cfab
  subdirs:
  - looksee
  - looksee-trip
