name: mello
version: 0.4.0

github: ejconlon/mello
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2024 Eric Conlon
synopsis: No-fuss syntax with s-expressions
description: Please see the README on GitHub at <https://github.com/ejconlon/mello#readme>
tested-with: GHC == 9.6.4
category: Parsing

defaults:
  local: ../defaults.yaml

extra-source-files:
- README.md

dependencies:
- base >= 4.12 && < 5
- bowtie >= 0.7 && < 0.8
- containers >= 0.6 && < 0.8
- foldl >= 1.4 && < 1.5
- looksee >= 0.8 && < 0.9
- mtl >= 2.3 && < 2.5
- prettyprinter >= 1.7 && < 1.8
- recursion-schemes >= 5.2 && < 5.3
- scientific >= 0.3 && < 0.4
- text >= 2.0 && < 2.2

library:
  source-dirs: src

tests:
  mello-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mello
    - looksee-trip >= 0.8 && < 0.9
    - daytripper >= 1.0 && < 1.1
    - prop-unit >= 1.0 && < 1.1

