name: mello
version: 0.1.0

github: ejconlon/mello
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2024 Eric Conlon
synopsis: No fuss syntax with s-expressions
description: Please see the README on GitHub at <https://github.com/ejconlon/mello#readme>
tested-with: GHC == 9.6.4

defaults:
  local: ../defaults.yaml

dependencies:
- base >= 4.12 && < 5

library:
  source-dirs: src

executables:
  mello-exe:
    main: Main.hs
    source-dirs: exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mello

tests:
  mello-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mello
    - tasty
    - tasty-hunit
